### PR TITLE
Update 2013-07-12-readings-in-distributed-systems.markdown

### PR DESCRIPTION
**Pull request by joshpadilla**
Swapped in the actual post URL page for the pull request link.
https://github.com/cmeiklejohn/cmeiklejohn.github.io/blob/master/_posts/2013-07-12-readings-in-distributed-systems.markdown?

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Mind a rebase here?

**Comment by joshpadilla** [comment]
If I understand the question correctly, sure a rebase is fine. Probably something I should have done instead of making all the branches per commit. Still wrapping my head around rebase feature of git since I haven't used it that much.

**Comment by joshpadilla** [comment]
Just to clarify, were you saying that I should do the rebase or is that something you would do? I don't mind either way. If it's on my end, I'll go off and make sure I'm issuing the correct git rebase command, which I'm sure it simple.

**Comment by cmeiklejohn** [comment]
I was taking if you could -- I'm happy to merge the change but right now it's conflicting with master, so you'll need to merge master in or rebase your changes, either approach works.

**Comment by joshpadilla** [comment]
I've actually been making my changes directly in the Github web editor, since they were just a few one line changes. So I'll need a little time to clone the repo, do the rebase commands, add, commit and push back to repo. No biggie, I think I can handle that.

**Comment by joshpadilla** [comment]
Ok I finally figured it out. I was able to resolve the conflicts right in the Github web editor. Simple enough, just didn't realize what I was looking at with the patch-3 and master branches. Hopefully that solves the merge issue.

**Pull request merged**
